### PR TITLE
Refactoring/testing

### PR DESCRIPTION
**Pull request by goatherd**
Refactoring the testsuite in order to cover all sniffs in a simplified fashion across all supported php environments.
- [x] prepare branch for unit testing (#20)
- [x] review phpcs integration
- [x] directly use phpcs classes for unit tests (quick approach)
- [x] abstract sniff properties
- [ ] drop actual literals from fixtures (cleanup)
- [x] review test suite
- [ ] document approach for developers
- [x] TravisCI validates built

### CODE REVIEW

**Comment by goatherd** [comment]
current status:
- getting all three php versions to give the same results
- running stable again
- using phpcs CLI class (instead of binary)
- abstracted literals from PHP group and standardized classes for further discussion

May do a deeper phpcs-integration to avoid some overhead. But performance is far from an issue and it would quiet likely add many LoC to the testsuite.

**Comment by goatherd** [comment]
@reneoelke could you please have a look at https://github.com/goatherd/Php54to55/blob/refactoring/testing/Sniffs/PHP/ForbiddenConstantNamesSniff.php ?

The class was stripped down to the essentials and the actual values reside in `properties/ForbiddenConstantNames.php` of the same directory. Abstracted logic was pushed to `/src` and `FoobugsStandards` namespace temporarily.

What was solved:
- injectable properties for unit testing (using late static binding)
- less code duplication
- standardizes coding (names, return types, code complexity)

I further separated the properties from the actual class to be injected on runtime.
The actual injection is yet rather simple (suffering from singletonitis) to be sophisticated later on.

I need feedback on the actual class design:
- is it okay to strip Sniffs down to this level?
- is it simple enough to extend?
- is the naming okay? (`fooRegisterTokens` and `fooProperties` properties and `FoobugsStandards` namespace)

On the directories:
- `/src` for abstractions acceptable? or is there a reason for some complex naming convention to include into `/Sniffs`?
- `properties/X.php` for `XSniff.php` to hold literal properties not effecting Sniff logic?

**Comment by reneoelke** [comment]
I think there are too much changes. The mean goal is to come public and stable in a short time. So it would be okay if all properties (etc.) are store in the class file. And its also okay (as i said) to have redundant code for know. It shouldn't be perfect but stable. In the next steps when we migrate the standard to the Snout application we can make it perfect. So please focus only the absolutely most important features:
- complete Sniffs (see [Migration55](http://php.net/manual/en/migration55.php))
- complete Tests (it's okay using the old test procedure (calling binary `snout` and check output))

All the other things we will implement in the next steps.

**Comment by goatherd** [comment]
@reneoelke adjusted to discussion: now only a Sniffs-path exists that holds two additional classes:
- a Helper
- a SniffBase class

The latter loads the helper that requires sniff scope and would have conflicted otherwise if detecting namespaces against multiple sniffs. You are free to code-duplicate it until the abstract sniff is dropped or you make the Helper fully static. Didn't care enough about it to do that much work.

So far only worked on PHP-group sniffs as those are not fully covered by tests.
Two known issues remain for the remaining sniffs:
- not all regular expression can be easily parsed
- phpcs tests deprecated function names against class namespace possibly reporting conflicts where there are none.

I will unit-fix the remaining sniffs of the PHP group and add from the PHP changelogs within the next days. Otherwise I won't touch a thing in the Sniffs/ path.

**Pull request merged**
